function [user, path, deverp] = derpa_syseval(~)
%DERPA_SYSEVAL Evaluates current system and gathers necessary information to run
%analyses. Also enures that directories specified exist and can be accessed.
%   Detailed explanation goes here

% Bring in specified dirs
evalin("base", "rawdir", rawdir)
evalin("base", "workdir", workdir)
evalin("base", "txtdir", txtdir)
evalin("base", "erpdir", erpdir)

% make structur of dirs for easy use
dirs = struct( ...
    'rawdir', {{rawdir}}, ...
    'workdir', {{workdir}}, ...
    'txtdir', {{txtdir}}, ...
    'erpdir', {{erpdir}});

deverp = struct( ...
    'dirs', {{dirs}}, ...
    'subject list', {{subjectlist}},...
    'data', {{}}, ...
    'run', {{}}, ...
    'winner', {{}}...
    );

end